#LOGGING
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: debug

#DATABASELOCAL
spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/fuelTracker
    username: admin
    password: pass123

  jpa:
    hibernate:
      ddl-auto: validate

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


