#LOGGING
logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate:
        SQL: INFO

#DATABASEDEV
spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/fuelTracker
    username: fuelTracker
    password: postgresDev