#LOGGING
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: debug

#DATABASELOCAL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fuelTracker
    username: fuelTracker
    password: fuelTracker