#LOGGING
logging:
  level:
    org:
      springframework:
        web: info
      hibernate:
        SQL: info

server:
  port: ${PORT:8080}

#DATABASE
spring:
  datasource:
    url: jdbc:postgresql://ec2-63-32-248-14.eu-west-1.compute.amazonaws.com:5432/ddvuf5hn0dev5m
    username: aujsnnktogcjnl
    password: 72d14798c79433b20d7a1676c4a57818c696056d82315e61cc2828f7b3512301
    maxActive: 5

  jpa:
    hibernate:
      ddl-auto: validate

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
