logging.level.org.springframework.web=DEBUG

spring.datasource.url=jdbc:postgresql://ec2-54-217-195-234.eu-west-1.compute.amazonaws.com/d5mf6o870iie25
spring.datasource.username=uvwkrmqjmdkhbh
spring.datasource.password=2aa1f3446cb82a45e8da33c9fb8408c6946bc0b9db0000f2b035942fa7f852e2

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.hibernate.ddl-auto= update
logging.level.org.hibernate.SQL=debug

jwt.expirationTime=4000000
jwt.secret=*e!lPHt0HP+}/z3:Yg`DFBIJEh-W!zGhdJqL8_,#Z0:+1bI4>z=Lm}S%i?5Jf

spring.cache.jcache.config=classpath:ehcache.xml
spring.liquibase.change-log=classpath:liquibase-changeLog.xml

spring.mvc.pathmatch.matching-strategy=ant-path-matcher
