#SERVER
server.port=8081
server.error.include-message=always
logging.level.org.springframework.web=DEBUG

#DATABASELOCAL
#spring.datasource.url=jdbc:postgresql://localhost:6432/fuelTracker
#spring.datasource.username=admin
#spring.datasource.password=pass123

#DATABASE
spring.datasource.url=jdbc:postgresql://ec2-18-202-156-92.eu-west-1.compute.amazonaws.com/ddv9p82g9resm6
spring.datasource.username=hvxwxrirsbsmvl
spring.datasource.password=db91f55e7d3aab1793a674958ea6418ca9e9b342f613508ffd4c177efe5907e2

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug

#JWT
jwt.expirationTime=4000000
jwt.secret=*e!lPHt0HP+}/z3:Yg`DFBIJEh-W!zGhdJqL8_,#Z0:+1bI4>z=Lm}S%i?5Jf

spring.mvc.pathmatch.matching-strategy=ant-path-matcher
