#LOGGING
logging:
  level:
    org:
      springframework:
        web: INFO
        cache: TRACE
      hibernate:
        SQL: INFO

#DATABASELOCAL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fuelTracker
  flyway:
    locations: classpath:migration
