CREATE TABLE CUSTOMERS
(
    CUS_ID          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL ,
    CUS_EMAIL       VARCHAR(255) NOT NULL ,
    CUS_ENABLED     BOOLEAN NOT NULL,
    CUS_FIRST_NAME  VARCHAR(255) NOT NULL ,
    CUS_LAST_NAME   VARCHAR(255) NOT NULL ,
    CUS_LOCKED      BOOLEAN NOT NULL,
    CUS_PASSWORD    VARCHAR(255) NOT NULL ,
    CUS_USER_ROLE   VARCHAR(255) NOT NULL ,
    CUS_USERNAME    VARCHAR(255) NOT NULL ,
    CUS_CREATED     TIMESTAMP NOT NULL,
    CUS_UPDATED     TIMESTAMP NOT NULL
);

CREATE TABLE VEHICLES
(
    VEH_ID  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL ,
    VEH_BRAND           VARCHAR(255) NOT NULL ,
    VEH_MODEL           VARCHAR(255) NOT NULL ,
    VEH_NAME            VARCHAR(255) NOT NULL ,
    VEH_PLATE_NUMBER    VARCHAR(255) NOT NULL ,
    VEH_TYPE            VARCHAR(255) NOT NULL ,
    VEH_YR_OF_PROD      INTEGER NOT NULL,
    VEH_CAPACITY        NUMERIC(10, 2) NOT NULL,
    VEH_CREATED         TIMESTAMP NOT NULL,
    VEH_UPDATED         TIMESTAMP NOT NULL,
    VEH_CUS_ID          INTEGER REFERENCES CUSTOMERS NOT NULL
);

create table refuel
(
    id         bigint generated by default as identity
        primary key,
    date       timestamp,
    free_tank  boolean not null,
    fuel       varchar(255),
    full_tank  boolean not null,
    litres     numeric(19, 2),
    odometer   bigint  not null,
    price      numeric(19, 2),
    total_cost numeric(19, 2),
    vehicle_id bigint
        constraint fksg51ccqhjn6gyiqnp0bch4n2n
            references vehicle
);

create table expense
(
    id          bigint generated by default as identity
        primary key,
    date        timestamp,
    note        varchar(255),
    odometer    bigint not null,
    total_price numeric(19, 2),
    vehicle_id  bigint
        constraint fkqc9bddyssi50h9lp7fhn5o5oy
            references vehicle
);




