create table CUSTOMERS
(
    CUS_ID          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CUS_EMAIL       VARCHAR(255) NOT NULL ,
    CUS_ENABLED     BOOLEAN NOT NULL,
    CUS_FIRST_NAME  VARCHAR(255) NOT NULL ,
    CUS_LAST_NAME   VARCHAR(255) NOT NULL ,
    CUS_LOCKED      BOOLEAN NOT NULL,
    CUS_PASSWORD    VARCHAR(255) NOT NULL ,
    CUS_USER_ROLE   VARCHAR(255) NOT NULL ,
    CUS_USERNAME    VARCHAR(255) NOT NULL ,
    CUS_CREATED     TIMESTAMP NOT NULL,
    CUS_UPDATED     TIMESTAMP NOT NULL,
);

create table vehicle
(
    id                 bigint generated by default as identity
        primary key,
    brand              varchar(255),
    model              varchar(255),
    name               varchar(255),
    plate_number       varchar(255),
    type               varchar(255),
    year_of_production integer not null,
    customer_id        bigint
        constraint fklwqsusjj6iodeb0df1b554vxq
            references customer
);

create table refuel
(
    id         bigint generated by default as identity
        primary key,
    date       timestamp,
    free_tank  boolean not null,
    fuel       varchar(255),
    full_tank  boolean not null,
    litres     numeric(19, 2),
    odometer   bigint  not null,
    price      numeric(19, 2),
    total_cost numeric(19, 2),
    vehicle_id bigint
        constraint fksg51ccqhjn6gyiqnp0bch4n2n
            references vehicle
);

create table expense
(
    id          bigint generated by default as identity
        primary key,
    date        timestamp,
    note        varchar(255),
    odometer    bigint not null,
    total_price numeric(19, 2),
    vehicle_id  bigint
        constraint fkqc9bddyssi50h9lp7fhn5o5oy
            references vehicle
);




