name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fuel-tracker-1"
          heroku_email: "notedeagle@gmail.com"
          justlogin: true
      - run: |
          heroku container:login
          heroku container:push web --app fuel-tracker-1
          heroku container:release web --app fuel-tracker-1